"use strict";

var Assert      = require("../Assert"),
    Exception   = require("../Exception/Exception");

/**
 *
 * Error generated by the Schema evaluation. This contain information about the
 * a schema evaluation result.
 *
 * @param {String}  message         The message or i18n template
 * @param {String}  messageData     The message template data
 * @param {*}       originalValue   The original value that was tested on the schema
 *
 */
var SchemaException = function(message, messageData, originalValue){

    // extend class from Exception
    Exception.apply(this, [message, messageData]);

    /**
     * Returns the value that originated the schema evaluation error.
     * @return {*}
     */
    this.getValue = function(){
        return originalValue;
    };

};

SchemaException.prototype = new Error();
SchemaException.prototype.constructor = SchemaException;

module.exports = SchemaException;
